version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: real_estate
    ports:
      - "3308:3306"
    volumes:
      - moson-realestate-main_mysql_data:/var/lib/mysql
    networks:
      - nextjs_network

  redis:
    image: redis:alpine
    container_name: redis_cache_new
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nextjs_network

volumes:
  moson-realestate-main_mysql_data:
    external: true
  redis_data: # 👉 새로 자동 생성될 내부 볼륨

networks:
  nextjs_network:
